### ISSUE TITLE
CONFIGURE script

### ISSUE THREAD

**Issue by archaic-archea** [q3k/ski#2]
Hey, I recently became interested in itanium, so I was searching around for the ski emulator, and this and one other thing is all I found.
But there isnt a configure script in either of them, is there anywhere I can find a full set of files?

**Comment by sskras** [comment]
In such cases I think the builder needs to run [`./autogen.sh`](https://github.com/q3k/ski/blob/master/autogen.sh):

Found some reference:
https://stackoverflow.com/questions/50044091/what-is-the-job-of-autogen-sh-when-building-a-c-package-on-linux/50044385#50044385

> The `autogen.sh` script generates the `configure` script (from `configure.ac`, using autoconf) and any files it needs (like creating `Makefile.in` from `Makefile.am` using automake). This requires autotools to be installed on your system, and it must be run when checking out the project from source control (if `configure` isn’t checked in).
> 
> People who download source tarballs can usually skip this step, because output of this step is included in source tarballs.

After a quick look at it I think `./autogen.sh` will use its' scripts from the [`macros`](https://github.com/q3k/ski/tree/master/macros) subdir.

**Comment by archaic-archea** [comment]
Ok, so I've gotten partially into it, I've downloaded dependencies, but all I get when running `autogen.sh` is this
```./configure: line 16604: syntax error near unexpected token `GSKI,'
./configure: line 16604: ` PKG_CHECK_MODULES(GSKI, libglade-2.0 libgnomeui-2.0 >= 1.110.0)'```

**Comment by sskras** [comment]
It completes successfully on Ubuntu 20.04 after installing `libelf-dev` and `libncurses-dev` packages:
```
$ ./configure
  ...
checking for bfd support... no
checking ski_elf.h usability... no
checking ski_elf.h presence... no
checking for ski_elf.h... no
checking for ldexp in -lm... yes
checking for tgetent in -lcurses... yes
checking for elf_begin in -lelf... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating ski.spec
config.status: creating ski-config
config.status: creating Makefile
config.status: creating macros/Makefile
config.status: creating src/Makefile
config.status: creating src/decoder/Makefile
config.status: creating src/encoder/Makefile
config.status: creating src/fake-xterm/Makefile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: linking src/missing/ski_elf.h to src/ski_elf.h
config.status: executing depfiles commands
config.status: executing libtool commands
```

Maybe version of your Autotools is different from verson of mine:
```
$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
```

**Comment by archaic-archea** [comment]
same autoconf version, I am now testing a brand spankin' new ubuntu install(in the form of a docker image), just `libtool`, `autoconf`, `git`, `libelf-dev`, and `libncurses-dev`, but it complains I dont have libtool installed for some reason. Did you manually build `libtool`?
Also my autoconf version is `2.69`.

**Comment by sskras** [comment]
EDIT: I did not build `libtool` manually.

It probably came as a dependency of some other package:
```
$ dpkg --list libtool
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libtool        2.4.6-14     all          Generic library support script
```

And `autogen.sh` actually runs `libtool` a bunch of times, so it's a definitely needed package.

What distro did you use in the previous tries?

**Comment by archaic-archea** [comment]
Tried it on Debian, as well as NixOS.
Could using apt be the issue on debian/ubuntu?

**Comment by sskras** [comment]
> Could using apt be the issue on debian/ubuntu?

I doubt that. I am using `apt` on this containerized Ubuntu guest (running on OpenVZ), and everything seems fine so far.
What is exact output of the failure?

I am attaching my `configure` script zipped: [configure.zip](https://github.com/q3k/ski/files/12187900/configure.zip)
In case you would like to compare with your first tries.  Although it's a big thing – more than half of megabyte:
```
$ wc configure
 18840  64620 554472 configure
```

**Comment by archaic-archea** [comment]
would you mind showing the Dockerfile you're using?
also the exact error is:
```**Error**: You must have `libtool' installed to compile ski.
Get ftp://ftp.gnu.org/pub/gnu/libtool-1.2d.tar.gz
(or a newer version if it is available)
The command '/bin/sh -c ./autogen.sh' returned a non-zero code: 1```
Which confuses me as I used apt to install libtool before I run the autogen file

**Comment by sskras** [comment]
Umm. I don't use Docker here – just a plain Ubuntu on my VPS account offered by our local hosting provider:
```
$ lsb_release -d
Description:    Ubuntu 20.04.2 LTS
```

Maybe our `PATH`s are different, Eg: https://github.com/madewokherd/wine-mono/issues/24#issuecomment-76274439 ?

Eureka, found the culprit – I forgot I am using some tools installed by the Pkgsrc manager:
```
$ command -v libtool
/home/sskras/pkg/bin/libtool
```

Looks like you need `libtool-bin` package in addition. Please excuse me my overlooked detail.

**Comment by archaic-archea** [comment]
Thats perfectly fine, thank you for figuring that out.
well something else occurred, its no longer causing issues with libtools, but its back to one of the other errors
```./configure: line 12079: syntax error near unexpected token `GSKI,'
./configure: line 12079: ` PKG_CHECK_MODULES(GSKI, libglade-2.0 libgnomeui-2.0 >= 1.110.0)'```

**Comment by sskras** [comment]
It looks like switching to Ubuntu doesn't make difference in comparison to Debian.

You could either attach the resulting `./configure` file (by zipping it first), or try comparing yours with mine.

**Comment by archaic-archea** [comment]
I'm gonna switch over to my NixOS computer and use the configure on that since its my main computer, but the error is the same, just with different line numbers.
```./configure: line 16583: syntax error near unexpected token `GSKI,'
./configure: line 16583: ` PKG_CHECK_MODULES(GSKI, libglade-2.0 libgnomeui-2.0 >= 1.110.0)'```
[configure.gz](https://github.com/q3k/ski/files/12188216/configure.gz)

**Comment by sskras** [comment]
You have a bit newer Autoconf here:
![image](https://github.com/q3k/ski/assets/7887758/19a14131-1536-4f53-864e-b682ab80d96d)

If you could get generated script by the 2.69 version, maybe the differences would get smaller (so it would be more meaningful to compare them to me).

**Comment by archaic-archea** [comment]
[configure.gz](https://github.com/q3k/ski/files/12188329/configure.gz)
there, that should be right

**Comment by archaic-archea** [comment]
ugh, I ended up just finding another repository thats more active and has prebuilt releases, thank you for all your help, if anyone would like the repo, here it is https://github.com/trofi/ski/releases/tag/v1.4.0

**Comment by sskras** [comment]
Nice!
